services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://kita_user:${MYSQL_PASSWORD:-kita_password}@db:3306/kita_dienstplan
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production-please}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-1440}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:8000}
      - SMTP_SERVER=${SMTP_SERVER:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USE_TLS=${SMTP_USE_TLS:-true}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - FROM_EMAIL=${FROM_EMAIL:-admin@kita.de}
      - FROM_NAME=${FROM_NAME:-Kita Dienstplan System}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY:-}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY:-}
      - VAPID_CONTACT=${VAPID_CONTACT:-mailto:admin@kita.de}
      - APP_URL=${APP_URL:-http://localhost:8000}
      - DEBUG=${DEBUG:-false}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./data/uploads:/app/uploads

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=kita_dienstplan
      - MYSQL_USER=kita_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-kita_password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # Optional: Nginx Reverse Proxy für HTTPS
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    profiles: ["with-nginx"]

