services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./kita_dienstplan.db
      - SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - ./backend:/app
      - ./data/backend:/app/data
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=kita_dienstplan
      - MYSQL_USER=kita_user
      - MYSQL_PASSWORD=kita_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

